/*
 * DO NOT MODIFY THIS FILE.  IT WAS GENERATED BY MIBMAN AND MAY BE REGENERATED LATER.
 */

/*
 *     Module Name: MibMan.h
 *	       Version: 1.00
 *    Generated On: $Date: 2006-12-12 20:33:58 $
 *	        Author: MibMan utility program
 *	      Language: Ansi C
 * Compile Options:
 * Compile defines:
 *	     Libraries:
 *    Link Options:
 *
 *    Entry Points:
 *
 *
 * Description.
 * =======================================================================
 *  This header file contains declarations for variables and functions 
 *  defined in MibMan.c that are used by the SNMP agent.
 *
 *
 * Edit Date/Ver   Edit Description
 * ==============  =======================================================
 *
 *
 */

#ifndef MIBMAN_H
#define MIBMAN_H

#include "man_agnt.h"






/*
 * List of struct variableStruct data types we use.  To conserve 
 * a different version of this structure is declared for each OID 
 * length in each subtree.
 */
struct mVariableStruct4
{
    u_char magic;                       /* passed to function as a hint */
    char type;                          /* type of variable */
    u_short acl;                        /* access control list for variable */
    snmpVarAccess readFunction;         /* function that will read the object*/
    u_char namelen;                     /* length of name below */
    snmpAgentIndexInfoType *indexInfo;  /* information about items indices*/
    int fieldCode;                      /* identifies which table field is being accessed*/
    manVarType *manInfo;                /* info for management variable that represents the object*/
    void *writeFn;                      /* write function for this object */
    oid name[4];                        /* object identifier of variable */
};
struct mVariableStruct2
{
    u_char magic;                       /* passed to function as a hint */
    char type;                          /* type of variable */
    u_short acl;                        /* access control list for variable */
    snmpVarAccess readFunction;         /* function that will read the object*/
    u_char namelen;                     /* length of name below */
    snmpAgentIndexInfoType *indexInfo;  /* information about items indices*/
    int fieldCode;                      /* identifies which table field is being accessed*/
    manVarType *manInfo;                /* info for management variable that represents the object*/
    void *writeFn;                      /* write function for this object */
    oid name[2];                        /* object identifier of variable */
};

#endif

