#include "snmp/snmp.h"

char *snmp_err[] = {
/* SNMP_ERR_NOERROR                 0 */ "NOERROR",
/* SNMP_ERR_TOOBIG                  1 */ "TOOBIG",
/* SNMP_ERR_NOSUCHNAME              2 */ "NOSUCHNAME",
/* SNMP_ERR_BADVALUE                3 */ "BADVALUE",
/* SNMP_ERR_READONLY                4 */ "READONLY",
/* SNMP_ERR_GENERR                  5 */ "GENERR",
/* SNMP_ERR_NOACCESS                6 */ "NOACCESS",
/* SNMP_ERR_WRONGTYPE               7 */ "WRONGTYPE",
/* SNMP_ERR_WRONGLENGTH             8 */ "WRONGLENGTH",
/* SNMP_ERR_WRONGENCODING           9 */ "WRONGENCODING",
/* SNMP_ERR_WRONGVALUE             10 */ "WRONGVALUE",
/* SNMP_ERR_NOCREATION             11 */ "NOCREATION",
/* SNMP_ERR_INCONSISTENTVALUE      12 */ "INCONISISTENVALUE"
/* SNMP_ERR_RESOURCEUNAVAILABLE    13 */ "RESOURCEUNAVAILABLE",
/* SNMP_ERR_COMMITFAILED           14 */ "COMMITFAILED",
/* SNMP_ERR_UNDOFAILED             15 */ "UNDOFAILED",
/* SNMP_ERR_AUTHORIZATIONERROR     16 */ "AUTHORIZATIONERROR",
/* SNMP_ERR_NOTWRITABLE            17 */ "NOTWRITEABLE",
/* SNMP_ERR_INCONSISTENTNAME       18 */ "INCONSISTENTNAME"
};
